---
defaults:
  ciphers:
    ike: aes128gcm16-sha2_512-prfsha512-ecp256!
    esp: aes128gcm16-sha2_512-ecp256!
  conn:
    subnet: 217.0.0.0/8
    dns: 8.8.8.8,8.8.4.4
    source_ip: 172.16.16.0/24

iface:
  device: "{{ ansible_interfaces | map('regex_replace', '(.*)', 'ansible_\\1') | map('extract', hostvars[inventory_hostname]) | selectattr('ipv4.address', 'equalto', ipsec.local_ip) | map(attribute='device') | first }}"

